sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
  - "7"
  - "8"
cache:
  directories: node_modules
branches:
  only: master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn
  - cd packages/@ngx-cache/core
  - yarn
  - cd ../../..
  - cd packages/@ngx-cache/platform-browser
  - yarn
  - cd ../../..
  - cd packages/@ngx-cache/platform-server
  - yarn
  - cd ../../..
  - cd packages/@ngx-cache/fs-storage
  - yarn
  - cd ../../..
  - sleep 3
after_failure:
  - cat /home/travis/build/fulls1z3/ngx-cache/npm-debug.log
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    on_success: change  # lifeSpan: [always|never|change] default: always
    on_failure: always  # lifeSpan: [always|never|change] default: always
    on_start: never     # lifeSpan: [always|never|change] default: always
