coverage:
  status:
    project:
      ngx-cache/core:
        target: 80%
        paths: packages/@ngx-cache/core
    project:
      ngx-cache/platform-browser:
        target: 80%
        paths: packages/@ngx-cache/platform-browser
    project:
      ngx-cache/platform-server:
        target: 80%
        paths: packages/@ngx-cache/platform-server
    project:
      ngx-cache/fs-storage:
        target: 80%
        paths: packages/@ngx-cache/fs-storage
